### ISSUE TITLE
Error: Unknown property "wishlistcomment" for BggCollectionItemDto

### ISSUE THREAD

**Issue by GamerKingFaiz** [LearningProcesss/boardgamegeekjsclient#19]
I'm querying the collection end point using `Alan How` as my username.

```js
  client.collection
    .query({
      username: 'Alan How',
      own: 1,
      excludesubtype: "boardgameexpansion",
    })
```

I encounter the following error:

```
(node:31220) UnhandledPromiseRejectionWarning: Error: Unknown property "wishlistcomment" for BggCollectionItemDto at [Source '{"name":"Small Islands","yearpublished":2018,"image":"https://cf.geekdo-images.com/wj0V1vCpR11kmq1EpWxxkw__original/img/m_YadJyiLlPK1rTXF4X60V9xyJY=/0x0/filters:format(jpeg)/pic3970233.jpg","thumbnail":"https://cf.geekdo-images.com/wj0V1vCpR11kmq1EpWxxkw__thumb/img/DyPhLsGnU_6DBS2CQ8yo5VcCaC4=/fit-in/200x150/filters:strip_icc()/pic3970233.jpg","status":{"@_own":1,"@_prevowned":0,"@_fortrade":0,"@_want":0,"@_wanttoplay":0,"@_wanttobuy":0,"@_wishlist":0,"@_preordered":0,"@_lastmodified":"2020-05-14 12:39:48"},"numplays":1,"wishlistcomment":"Carcasonne like","objectid":236248,"collid":66004367,"objecttype":"thing","subtype":"boardgame"}']
    at new t (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:21428)
    at e.parseJsonCreator (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:82772)
    at e.deepTransform (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:75298)
    at e.parseIterable (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:99411)
    at e.deepTransform (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:75380)
    at e.parseJsonClassType (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:89686)
    at e.parseJsonCreator (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:82526)
    at e.deepTransform (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:75298)
    at e.parseIterable (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:99411)
    at e.deepTransform (C:\Users\gamek\Documents\Websites\shouldiplay-api\node_modules\jackson-js\dist\lib.node.js:16:75380)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:31220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Note:** You may need to query this username twice as described in #18.

**Comment by LearningProcesss** [comment]
Hi, 
thank you for pointing out this problem!
I will add this property that i was not aware of to the response model since my collection has no whishlist comment.
