### ISSUE TITLE
`TypeError: Cannot read property '0' of undefined` on thing endpoint

### ISSUE THREAD

**Issue by GamerKingFaiz** [LearningProcesss/boardgamegeekjsclient#25]
I'm trying to query the thing endpoint as such:
```js
      client.thing
        .query({ id: games, stats: 1 })
        .then((result) => res.send(result));
```
Where `games` is the following array of games (all the game ids from the [paxtt collection](https://boardgamegeek.com/user/paxtt)):
```json
[250621,257668,226255,340790,279307,279306,345121,271447,187104,253618,271512,432,68448,173346,346703,302260,239472,172818,231398,202408,267814,267813,191189,267127,281946,264647,2272,230085,31260,247367,256442,161970,6249,181293,48726,250355,307243,278783,234487,228959,245704,124742,17329,212388,271530,285967,311193,262135,250834,142271,13122,309319,174614,74,58253,814,283393,140934,179803,144734,236457,256390,222862,255363,15987,285773,225729,246150,160432,254713,276923,69789,138233,108784,223762,273284,55253,248490,223201,175418,286658,225449,231581,446,127506,10093,230802,256226,287954,266164,199223,254585,170825,269917,293,206540,27225,244267,223740,251247,224678,204175,2458,173776,234477,59936,39375,288781,268471,298528,89409,278305,2425,165950,271528,299592,243780,334187,342073,10547,258036,317985,34219,171233,263051,226445,187383,235555,165952,277927,230244,148282,265316,156858,253861,253861,262215,258210,3427,2453,206504,170216,195856,27490,245710,244331,274688,1293,11,261529,170922,343905,276622,157973,252556,131835,271529,166286,206175,148767,224517,335,332386,139898,337765,257726,130393,172308,275913,127505,203102,137909,149853,201006,172081,11416,552,193681,284229,316113,38032,171499,268255,69120,338957,214,246761,275916,283155,199383,40270,238992,335271,264660,41,5048,344404,295607,176651,145888,281248,232824,333907,159503,208804,171131,255455,1126,269789,822,4390,256065,16216,145014,262562,231484,245934,252712,233006,263918,194233,242409,295947,71906,114903,266141,256569,84876,213370,155426,279135,228504,245824,57390,194286,13,244144,67239,125921,218129,102794,284818,175117,242574,232832,209685,218479,248900,253185,267378,227072,172287,256507,196026,245598,224830,229638,240567,251420,230916,25695,162974,239188,221122,5432,289786,167283,478,267370,133528,214880,162152,233247,345118,201808,216132,40765,34297,283289,262211,1294,1561,198328,178900,220775,249821,220774,198773,238972,245638,95945,196240,264982,192934,5782,268252,269160,223742,158899,299027,118174,147151,247314,124361,112,2961,2719,190073,140236,269511,269595,277662,98351,269725,344277,39463,298572,227273,204027,278402,131357,260382,180674,187653,230528,317981,163656,324856,284083,138026,215371,264586,256570,273092,244274,192457,330608,246784,228133,280480,269618,253344,175541,197321,275973,38437,226213,223049,28259,249411,143986,202977,105602,289802,208134,193877,248722,111124,193670,246147,101685,184522,150376,243430,177921,260922,156129,225694,283649,169654,274566,104162,223726,256788,9061,152162,194594,310632,230267,216734,244271,266966,184917,270377,170477,265583,220624,221194,318009,317457,483,258244,225316,91312,256382,39856,172164,179182,199793,5737,36218,262547,253786,334379,232090,124548,158267,343559,215311,217554,329151,193840,254191,232219,212378,172866,126206,235655,1042,226501,272993,283748,184704,172933,172540,136356,194880,205831,257415,263317,244916,255618,36235,283355,329713,319999,262208,59946,328478,207062,134596,271055,279254,229491,131366,100423,146021,286431,216403,90050,68425,938,228378,83157,171339,36554,175621,50685,131121,196354,88594,282291,253214,206299,249381,206718,133848,270960,199792,131006,1159,155703,201248,201825,277003,253074,163976,201846,272682,184247,172225,176371,254994,188530,206082,249670,294233,140218,13823,307971,220780,135779,232918,293889,209280,337262,254193,216600,223040,221230,271045,231664,231666,231665,256801,277597,198609,96704,177736,847,163839,200954,257733,240744,226605,233020,231991,138161,227162,206941,173784,157354,199478,180421,100901,244609,142829,261165,223215,275969,256478,334794,256701,258,175324,159504,280896,132758,172,144567,136063,65244,245271,72376,302723,287941,37904,296912,244049,184672,288169,245645,119506,276880,344407,66188,248956,197443,258308,203430,253743,246693,181279,171273,258389,343526,27787,220308,248443,137811,31481,173090,159492,2921,179701,307098,229218,275530,103343,180602,236461,179259,176914,42776,137669,307772,145393,257321,286215,30539,120447,193248,258665,241245,253719,83195,118705,37046,259897,32751,257273,226356,258444,21985,176,246192,285232,301716,265188,214898,293556,192547,217553,184346,294237,132620,13230,278120,175219,195539,316622,265399,292795,234120,230542,238182,295147,255615,192508,254681,277400,93,142992,330036,193738,332421,57201,156501,168054,212402,254513,231327,173804,256159,140779,4143,250458,251890,322250,269144,227254,233848,158600,216381,234,325414,194626,223750,199042,200058,257205,228234,186721,119639,131904,6887,227789,288876,8450,382,224272,272132,164529,243231,195314,231554,311322,252892,299252,198994,79067,261979,8203,302267,240167,260332,245444,295957,255805,207336,218050,169256,239621,202026,159536,216070,287219,159087,176898,177524,235690,28,219232,191894,191862,255674,246228,154203,338760,217776,95893,331029,144239,252323,233678,215308,311266,311191,181797,261403,63888,206051,174611,161882,158548,271088,250963,231558,285895,204755,176494,185589,148949,235488,246709,327711,271324,271046,54043,28023,253215,266769,193621,324246,229954,191687,8098,247360,174991,245431,254640,320390,228425,200147,232254,183251,274432,198190,191055,252446,299172,322039,122515,257501,212516,215614,299684,250561,204602,3699,205826,160499,70323,126996,107529,276281,204583,281960,340041,223953,310371,277611,181810,247733,227758,171879,278989,183420,266083,1219,228882,160851,192927,29368,210052,153479,220784,129437,275467,140620,256831,260757,196976,326970,306173,104617,241266,328479,236301,330038,268936,65781,40237,136991,316412,169550,823,175755,126443,20437,110327,203993,50,311918,197707,158339,312484,198525,254399,129622,129622,196326,339905,66,242804,228169,245643,1,143884,340364,96848,329529,341919,248763,180157,301257,283863,9440,164198,230080,258041,199,176734,291847,276025,9590,283948,29223,230361,285774,272541,139030,159581,325564,211734,235839,2392,280453,224997,268493,209010,242529,193214,252484,192120,266304,175861,244794,25292,233570,255639,114991,166109,559,248861,268677,318977,338834,239840,169427,151347,200610,244992,284653,225818,197433,109932,221677,285533,344768,118,173115,251622,238393,255526,313698,209001,245053,316972,213862,265681,36345,4209,330403,270239,197414,122298,296063,175199,305985,214293,323317,162315,182062,174925,344273,171211,286735,1927,112869,31920,112991,25071,208256,144325,171199,129359,198776,229640,164031,302244,180816,257700,213670,86955,323002,341256,234396,191004,331571,226320,181304,269537,915,234691,244191,275215,249746,54433,257836,253106,157809,255990,187617,246663,256643,72321,290733,245058,205716,157413,232478,208895,272697,244711,257633,13308,337391,306709,279869,8522,13511,181615,234216,217449,187347,269752,102148,294693,158883,138704,194879,25554,284435,231567,65515,234277,249505,291572,273477,231733,260156,123219,283867,5206,279169,94571,5259,270314,230089,211940,270445,184267,276004,281152,251412,1234,179275,263155,147949,160477,3737,255507,245950,284949,174646,287084,322588,222542,172931,317941,273755,176803,268679,117838,311330,37120,154003,152237,274349,223278,266810,239464,140163,30549,260428,329670,301919,192153,234671,150658,248167,248584,2639,217861,141572,241066,207010,280136,284429,266524,15110,9006,2593,257966,144041,163412,256960,128780,257732,1797,169215,155465,97803,252479,231032,210274,88521,218603,209282,98229,284108,197571,246200,271036,244505,232520,256730,73538,172560,140,218996,125548,99808,252929,204879,23094,232201,257077,251660,163119,247576,274960,226264,172385,254619,249500,137155,180974,207783,2651,203780,258148,268251,87890,209945,6549,169459,137348,182604,218179,277692,181796,219708,3076,228341,54221,114050,67928,1419,187988,36648,215469,266830,244521,176396,131200,681,232043,217372,319767,274093,624,25669,39813,131260,208775,12,254386,231876,28143,329082,253635,170042,210908,251678,245654,336962,314401,177639,272078,42452,235071,337493,256623,250878,208024,24310,33451,66510,142402,212662,244258,330097,249578,193668,36946,222906,120426,244228,294230,170604,135116,282287,41114,128882,34887,104363,241831,91514,218333,220926,221372,194232,51,118695,161719,323873,202583,205896,181,1829,126789,262114,66056,257759,227515,321108,234093,232666,203215,18,231477,231476,240006,235653,283387,255683,254613,169426,237182,201,165986,168788,266722,285265,278359,180943,252854,9220,168215,268680,199561,35395,347146,158900,234101,175086,276830,194655,244330,230266,148533,372,172235,234846,256669,438,291453,320,202982,169786,108745,265683,188834,217099,216428,25021,250951,247143,223855,146408,102652,305986,228855,24068,159405,279928,347550,112092,253087,229741,15062,246297,200359,244115,6284,157969,204305,201446,298352,339614,75547,183361,220672,256967,178450,202426,333539,278553,270673,188614,280281,149910,92415,23329,216629,271785,40692,309630,97786,246684,122522,162559,113289,337389,38054,271038,329839,174837,223327,255255,223376,296626,181819,235014,2407,37196,260407,38453,242302,299074,142079,251832,266179,243358,14535,220547,252277,221832,196105,66505,171129,162886,149119,148228,293296,63268,227545,166384,229006,1035,287780,289427,243993,221233,102104,4095,230253,268276,193737,193949,117985,178613,79127,248567,5258,271896,1897,262262,245357,223770,224937,2770,27833,121410,162007,329845,230570,205459,2680,34635,20436,251854,1917,257669,202584,91534,132799,286790,233312,333055,207910,265684,123260,299372,313000,337787,93260,231960,257445,170917,201971,234316,162286,16933,276641,328826,139443,260383,310194,2653,192291,133473,271869,244141,203716,316786,257667,248002,475,153,70919,130176,34119,27627,908,908,30645,286096,129556,146278,276416,236709,294448,247694,221369,46213,173761,95386,273433,229853,120677,20022,167791,272427,186695,270138,226322,254923,226634,257411,1943,188920,159011,175961,145371,321215,20806,282438,182028,503,209951,53953,116998,346296,9209,309113,14996,205125,225244,253284,31627,202670,22825,42,54,34373,581,340166,155708,148951,257283,201921,180852,244536,227693,265736,258723,123540,257197,268250,261901,236365,235360,235344,257198,34599,256479,192135,294348,210900,265017,35815,216632,226146,255633,338628,283864,297204,102680,175293,163805,337961,278915,257527,216439,242639,309852,202582,1412,282171,36407,18463,258104,242325,148291,256303,281442,240822,257073,1410,284584,15261,16992,124172,229414,341918,196392,233078,12493,206904,12333,134352,234621,234438,126163,16986,46396,31479,266421,34969,219100,268682,38159,326400,306735,247763,217085,179172,340466,159566,230303,230305,274637,335764,2223,234190,260635,226588,286829,170561,269526,257058,170416,252399,120906,208360,189453,2596,104006,27532,296667,194690,231223,257076,143981,239877,266842,257769,247980,249259,253499,206803,195560,274364,333,262543,335541,31016,264806,88228,166859,339789,233867,229265,233206,925,245422,232405,201054,190082,93563,218126,298371,244654,266192,222853,318560,20100,71655,203411,274296,208480,186690,179245,342848,270635,336622,315937,163602,82222,247191,2243,213893,247185,244114,224271,320781,43022,129290,312289,283294,220741,281264,322589,6830,180853,2247,284107,249289,113924,62871,29387,333116,231673,79312,155633,10167,41627,257204,338862,348097,335733,261431]
```

Here is the full stack trace:
```
(node:58616) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:12:57
    at new Promise (<anonymous>)
    at BggThingDtoParser.jsonToDto (C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:11:16)
    at BggThingClient.<anonymous> (C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\client\concrete\BggThingClient.js:26:41)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\client\concrete\BggThingClient.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:58616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)       
(node:58616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LearningProcesss** [comment]
You are pushing too hard BGG itself!

![bgguritoolarge](https://user-images.githubusercontent.com/38817460/153509118-f930e151-6ca9-42e6-bab5-c03b8a187558.png)

Consider another approach to gather informations from huge list like that.
Try to chunk in small pieces. Max 5 element per request maybe.

**Comment by GamerKingFaiz** [comment]
> You are pushing too hard BGG itself!

LOL!

Okay, I know this issue then. I actually have worked around this issue on my website [here](https://github.com/GamerKingFaiz/bgg-collection/blob/4754f1e241a92442de226177289859e0f86b9bde/src/Containers/App.js#L70). I found that the items endpoint can only process about 1200 games in one call, so I split the results into length 1200 arrays.

I guess I was hoping that your library would've taken care of that. 😁

**Comment by nikmd23** [comment]
I'm running into the same issue with `collection`, but I'm not generating a huge URI, I'm just passing my username over" `bgg.collection.query({ username: 'nikmd23' })`

**Comment by LearningProcesss** [comment]
> I'm running into the same issue with `collection`, but I'm not generating a huge URI, I'm just passing my username over" `bgg.collection.query({ username: 'nikmd23' })`

Can't reproduce with 1.6.0 . Let me know. If persist, open new dedicated issue.

**Comment by LearningProcesss** [comment]
> I'm trying to query the thing endpoint as such:
> 
> ```js
>       client.thing
>         .query({ id: games, stats: 1 })
>         .then((result) => res.send(result));
> ```
> 
> Where `games` is the following array of games (all the game ids from the [paxtt collection](https://boardgamegeek.com/user/paxtt)):
> 
> ```json
> [250621,257668,226255,340790,279307,279306,345121,271447,187104,253618,271512,432,68448,173346,346703,302260,239472,172818,231398,202408,267814,267813,191189,267127,281946,264647,2272,230085,31260,247367,256442,161970,6249,181293,48726,250355,307243,278783,234487,228959,245704,124742,17329,212388,271530,285967,311193,262135,250834,142271,13122,309319,174614,74,58253,814,283393,140934,179803,144734,236457,256390,222862,255363,15987,285773,225729,246150,160432,254713,276923,69789,138233,108784,223762,273284,55253,248490,223201,175418,286658,225449,231581,446,127506,10093,230802,256226,287954,266164,199223,254585,170825,269917,293,206540,27225,244267,223740,251247,224678,204175,2458,173776,234477,59936,39375,288781,268471,298528,89409,278305,2425,165950,271528,299592,243780,334187,342073,10547,258036,317985,34219,171233,263051,226445,187383,235555,165952,277927,230244,148282,265316,156858,253861,253861,262215,258210,3427,2453,206504,170216,195856,27490,245710,244331,274688,1293,11,261529,170922,343905,276622,157973,252556,131835,271529,166286,206175,148767,224517,335,332386,139898,337765,257726,130393,172308,275913,127505,203102,137909,149853,201006,172081,11416,552,193681,284229,316113,38032,171499,268255,69120,338957,214,246761,275916,283155,199383,40270,238992,335271,264660,41,5048,344404,295607,176651,145888,281248,232824,333907,159503,208804,171131,255455,1126,269789,822,4390,256065,16216,145014,262562,231484,245934,252712,233006,263918,194233,242409,295947,71906,114903,266141,256569,84876,213370,155426,279135,228504,245824,57390,194286,13,244144,67239,125921,218129,102794,284818,175117,242574,232832,209685,218479,248900,253185,267378,227072,172287,256507,196026,245598,224830,229638,240567,251420,230916,25695,162974,239188,221122,5432,289786,167283,478,267370,133528,214880,162152,233247,345118,201808,216132,40765,34297,283289,262211,1294,1561,198328,178900,220775,249821,220774,198773,238972,245638,95945,196240,264982,192934,5782,268252,269160,223742,158899,299027,118174,147151,247314,124361,112,2961,2719,190073,140236,269511,269595,277662,98351,269725,344277,39463,298572,227273,204027,278402,131357,260382,180674,187653,230528,317981,163656,324856,284083,138026,215371,264586,256570,273092,244274,192457,330608,246784,228133,280480,269618,253344,175541,197321,275973,38437,226213,223049,28259,249411,143986,202977,105602,289802,208134,193877,248722,111124,193670,246147,101685,184522,150376,243430,177921,260922,156129,225694,283649,169654,274566,104162,223726,256788,9061,152162,194594,310632,230267,216734,244271,266966,184917,270377,170477,265583,220624,221194,318009,317457,483,258244,225316,91312,256382,39856,172164,179182,199793,5737,36218,262547,253786,334379,232090,124548,158267,343559,215311,217554,329151,193840,254191,232219,212378,172866,126206,235655,1042,226501,272993,283748,184704,172933,172540,136356,194880,205831,257415,263317,244916,255618,36235,283355,329713,319999,262208,59946,328478,207062,134596,271055,279254,229491,131366,100423,146021,286431,216403,90050,68425,938,228378,83157,171339,36554,175621,50685,131121,196354,88594,282291,253214,206299,249381,206718,133848,270960,199792,131006,1159,155703,201248,201825,277003,253074,163976,201846,272682,184247,172225,176371,254994,188530,206082,249670,294233,140218,13823,307971,220780,135779,232918,293889,209280,337262,254193,216600,223040,221230,271045,231664,231666,231665,256801,277597,198609,96704,177736,847,163839,200954,257733,240744,226605,233020,231991,138161,227162,206941,173784,157354,199478,180421,100901,244609,142829,261165,223215,275969,256478,334794,256701,258,175324,159504,280896,132758,172,144567,136063,65244,245271,72376,302723,287941,37904,296912,244049,184672,288169,245645,119506,276880,344407,66188,248956,197443,258308,203430,253743,246693,181279,171273,258389,343526,27787,220308,248443,137811,31481,173090,159492,2921,179701,307098,229218,275530,103343,180602,236461,179259,176914,42776,137669,307772,145393,257321,286215,30539,120447,193248,258665,241245,253719,83195,118705,37046,259897,32751,257273,226356,258444,21985,176,246192,285232,301716,265188,214898,293556,192547,217553,184346,294237,132620,13230,278120,175219,195539,316622,265399,292795,234120,230542,238182,295147,255615,192508,254681,277400,93,142992,330036,193738,332421,57201,156501,168054,212402,254513,231327,173804,256159,140779,4143,250458,251890,322250,269144,227254,233848,158600,216381,234,325414,194626,223750,199042,200058,257205,228234,186721,119639,131904,6887,227789,288876,8450,382,224272,272132,164529,243231,195314,231554,311322,252892,299252,198994,79067,261979,8203,302267,240167,260332,245444,295957,255805,207336,218050,169256,239621,202026,159536,216070,287219,159087,176898,177524,235690,28,219232,191894,191862,255674,246228,154203,338760,217776,95893,331029,144239,252323,233678,215308,311266,311191,181797,261403,63888,206051,174611,161882,158548,271088,250963,231558,285895,204755,176494,185589,148949,235488,246709,327711,271324,271046,54043,28023,253215,266769,193621,324246,229954,191687,8098,247360,174991,245431,254640,320390,228425,200147,232254,183251,274432,198190,191055,252446,299172,322039,122515,257501,212516,215614,299684,250561,204602,3699,205826,160499,70323,126996,107529,276281,204583,281960,340041,223953,310371,277611,181810,247733,227758,171879,278989,183420,266083,1219,228882,160851,192927,29368,210052,153479,220784,129437,275467,140620,256831,260757,196976,326970,306173,104617,241266,328479,236301,330038,268936,65781,40237,136991,316412,169550,823,175755,126443,20437,110327,203993,50,311918,197707,158339,312484,198525,254399,129622,129622,196326,339905,66,242804,228169,245643,1,143884,340364,96848,329529,341919,248763,180157,301257,283863,9440,164198,230080,258041,199,176734,291847,276025,9590,283948,29223,230361,285774,272541,139030,159581,325564,211734,235839,2392,280453,224997,268493,209010,242529,193214,252484,192120,266304,175861,244794,25292,233570,255639,114991,166109,559,248861,268677,318977,338834,239840,169427,151347,200610,244992,284653,225818,197433,109932,221677,285533,344768,118,173115,251622,238393,255526,313698,209001,245053,316972,213862,265681,36345,4209,330403,270239,197414,122298,296063,175199,305985,214293,323317,162315,182062,174925,344273,171211,286735,1927,112869,31920,112991,25071,208256,144325,171199,129359,198776,229640,164031,302244,180816,257700,213670,86955,323002,341256,234396,191004,331571,226320,181304,269537,915,234691,244191,275215,249746,54433,257836,253106,157809,255990,187617,246663,256643,72321,290733,245058,205716,157413,232478,208895,272697,244711,257633,13308,337391,306709,279869,8522,13511,181615,234216,217449,187347,269752,102148,294693,158883,138704,194879,25554,284435,231567,65515,234277,249505,291572,273477,231733,260156,123219,283867,5206,279169,94571,5259,270314,230089,211940,270445,184267,276004,281152,251412,1234,179275,263155,147949,160477,3737,255507,245950,284949,174646,287084,322588,222542,172931,317941,273755,176803,268679,117838,311330,37120,154003,152237,274349,223278,266810,239464,140163,30549,260428,329670,301919,192153,234671,150658,248167,248584,2639,217861,141572,241066,207010,280136,284429,266524,15110,9006,2593,257966,144041,163412,256960,128780,257732,1797,169215,155465,97803,252479,231032,210274,88521,218603,209282,98229,284108,197571,246200,271036,244505,232520,256730,73538,172560,140,218996,125548,99808,252929,204879,23094,232201,257077,251660,163119,247576,274960,226264,172385,254619,249500,137155,180974,207783,2651,203780,258148,268251,87890,209945,6549,169459,137348,182604,218179,277692,181796,219708,3076,228341,54221,114050,67928,1419,187988,36648,215469,266830,244521,176396,131200,681,232043,217372,319767,274093,624,25669,39813,131260,208775,12,254386,231876,28143,329082,253635,170042,210908,251678,245654,336962,314401,177639,272078,42452,235071,337493,256623,250878,208024,24310,33451,66510,142402,212662,244258,330097,249578,193668,36946,222906,120426,244228,294230,170604,135116,282287,41114,128882,34887,104363,241831,91514,218333,220926,221372,194232,51,118695,161719,323873,202583,205896,181,1829,126789,262114,66056,257759,227515,321108,234093,232666,203215,18,231477,231476,240006,235653,283387,255683,254613,169426,237182,201,165986,168788,266722,285265,278359,180943,252854,9220,168215,268680,199561,35395,347146,158900,234101,175086,276830,194655,244330,230266,148533,372,172235,234846,256669,438,291453,320,202982,169786,108745,265683,188834,217099,216428,25021,250951,247143,223855,146408,102652,305986,228855,24068,159405,279928,347550,112092,253087,229741,15062,246297,200359,244115,6284,157969,204305,201446,298352,339614,75547,183361,220672,256967,178450,202426,333539,278553,270673,188614,280281,149910,92415,23329,216629,271785,40692,309630,97786,246684,122522,162559,113289,337389,38054,271038,329839,174837,223327,255255,223376,296626,181819,235014,2407,37196,260407,38453,242302,299074,142079,251832,266179,243358,14535,220547,252277,221832,196105,66505,171129,162886,149119,148228,293296,63268,227545,166384,229006,1035,287780,289427,243993,221233,102104,4095,230253,268276,193737,193949,117985,178613,79127,248567,5258,271896,1897,262262,245357,223770,224937,2770,27833,121410,162007,329845,230570,205459,2680,34635,20436,251854,1917,257669,202584,91534,132799,286790,233312,333055,207910,265684,123260,299372,313000,337787,93260,231960,257445,170917,201971,234316,162286,16933,276641,328826,139443,260383,310194,2653,192291,133473,271869,244141,203716,316786,257667,248002,475,153,70919,130176,34119,27627,908,908,30645,286096,129556,146278,276416,236709,294448,247694,221369,46213,173761,95386,273433,229853,120677,20022,167791,272427,186695,270138,226322,254923,226634,257411,1943,188920,159011,175961,145371,321215,20806,282438,182028,503,209951,53953,116998,346296,9209,309113,14996,205125,225244,253284,31627,202670,22825,42,54,34373,581,340166,155708,148951,257283,201921,180852,244536,227693,265736,258723,123540,257197,268250,261901,236365,235360,235344,257198,34599,256479,192135,294348,210900,265017,35815,216632,226146,255633,338628,283864,297204,102680,175293,163805,337961,278915,257527,216439,242639,309852,202582,1412,282171,36407,18463,258104,242325,148291,256303,281442,240822,257073,1410,284584,15261,16992,124172,229414,341918,196392,233078,12493,206904,12333,134352,234621,234438,126163,16986,46396,31479,266421,34969,219100,268682,38159,326400,306735,247763,217085,179172,340466,159566,230303,230305,274637,335764,2223,234190,260635,226588,286829,170561,269526,257058,170416,252399,120906,208360,189453,2596,104006,27532,296667,194690,231223,257076,143981,239877,266842,257769,247980,249259,253499,206803,195560,274364,333,262543,335541,31016,264806,88228,166859,339789,233867,229265,233206,925,245422,232405,201054,190082,93563,218126,298371,244654,266192,222853,318560,20100,71655,203411,274296,208480,186690,179245,342848,270635,336622,315937,163602,82222,247191,2243,213893,247185,244114,224271,320781,43022,129290,312289,283294,220741,281264,322589,6830,180853,2247,284107,249289,113924,62871,29387,333116,231673,79312,155633,10167,41627,257204,338862,348097,335733,261431]
> ```
> 
> Here is the full stack trace:
> 
> ```
> (node:58616) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
>     at C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:12:57
>     at new Promise (<anonymous>)
>     at BggThingDtoParser.jsonToDto (C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:11:16)
>     at BggThingClient.<anonymous> (C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\client\concrete\BggThingClient.js:26:41)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\...\node_modules\boardgamegeekclient\dist\cjs\client\concrete\BggThingClient.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:58616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function 
> without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)       
> (node:58616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Hi @GamerKingFaiz 

Release 1.7.0 introduce two new features:
- queryWithProgress: available on Thing, Family and Forumlist client, gives the possibility to chunk a large ids request and notify with progression event.
- query method has now auto chunk built in functionality to handle large number ids.

Checkout the documentations for more details!
